REM   Script: Homework4 (19.12.2019) - 2 (Cities without departments - JOIN, NOT IN, EXISTS)
REM   SQL for Novice (part 4 task 2)

SELECT C.CITY 
FROM HR.DEPARTMENTS D 
RIGHT JOIN HR.LOCATIONS C 
    ON D.LOCATION_ID = C.LOCATION_ID 
    WHERE DEPARTMENT_ID IS NULL 
    ORDER BY C.CITY;

SELECT C.CITY 
FROM HR.LOCATIONS C 
WHERE C.LOCATION_ID NOT IN (SELECT LOCATION_ID 
                             FROM HR.DEPARTMENTS) 
ORDER BY C.CITY;

SELECT C.CITY 
FROM HR.LOCATIONS C 
WHERE NOT EXISTS (SELECT 1 
                FROM HR.DEPARTMENTS D 
                WHERE C.LOCATION_ID = D.LOCATION_ID 
                AND ROWNUM < 2) 
ORDER BY C.CITY;

