REM   Script: Homework4 (19.12.2019) - 4 (longest period)
REM   SQL for Novice (part 4 task 4)

SELECT  EMPLOYEE_ID, LONGEST_PER 
FROM (SELECT EMPLOYEE_ID, LONGEST_PER, ROWNUM AS R 
    FROM  
        (SELECT E.EMPLOYEE_ID, ROUND (E.END_DATE - E.START_DATE) AS LONGEST_PER 
        FROM HR.JOB_HISTORY E 
        ORDER BY ROUND (E.END_DATE - E.START_DATE) DESC) 
    ) 
WHERE R<=3;

