REM   Script: Session 01
REM   HOMEWORK 1 (SQL for Novice) 11.12.2019

SELECT (TO_CHAR (TO_DATE ('31.12', 'DD.MM'),'ddd') - (TO_CHAR (SYSDATE, 'ddd'))) AS DAYS 
FROM DUAL;

SELECT FIRST_NAME, LAST_NAME 
FROM HR.EMPLOYEES 
WHERE ((SYSDATE - HIRE_DATE) / 365 > 5 
    OR SALARY > 15000);

SELECT LAST_NAME 
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID = 10;

SELECT LAST_NAME 
FROM HR.EMPLOYEES 
WHERE SALARY > 2000;

SELECT LAST_NAME 
FROM HR.EMPLOYEES E 
WHERE (EXTRACT (YEAR FROM E.HIRE_DATE)) <= 2001;

