REM   Script: Homework3 (16.12.2019)
REM   Homework 3 (SQL for Novice)

SELECT D.JOB_ID, D.JOB_TITLE  
FROM HR.JOBS D  
LEFT JOIN HR.EMPLOYEES E  
ON D.JOB_ID = E.JOB_ID  
WHERE E.EMPLOYEE_ID IS NULL  
ORDER BY D.JOB_ID ;

SELECT D.DEPARTMENT_NAME, C.JOB_ID, COUNT (E.EMPLOYEE_ID) AS Emp_Amount 
FROM HR.DEPARTMENTS D 
    LEFT JOIN HR.EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
    LEFT JOIN HR.JOBS C ON E.JOB_ID = C.JOB_ID 
GROUP BY D.DEPARTMENT_NAME, C.JOB_ID 
ORDER BY D.DEPARTMENT_NAME;

